# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-27 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TripApp', '0002_auto_20190524_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to='LoginRegistration.User'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_attendants',
            field=models.ManyToManyField(null=True, related_name='joined_trips', to='LoginRegistration.User'),
        ),
    ]
